# Generated by Django 3.1.5 on 2021-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='samplesns/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
